services:
  preloader:
    image: docker:cli
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["sh", "-c", "docker pull suyash5053/chromium-vnc-cdp"]

  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - preloader
    networks:
      - app-network

networks:
  app-network:
    name: app-network-global
    driver: bridge
